FROM python:3.11-slim

WORKDIR /app

COPY requirements_minimal.txt .
RUN pip install -r requirements_minimal.txt

COPY app_minimal.py .

EXPOSE 8080

CMD gunicorn app_minimal:app --bind 0.0.0.0:$PORT 