services:
  - type: web
    name: carta-automatica
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PORT
        value: 8080
    healthCheckPath: /health 